server:
  port: 8080
  address: 0.0.0.0

app:
  base-url: ${APP_BASE_URL}
spring:
  application:
    name: Url Shortener

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver